# The URL the site will be built for
base_url = "${BASE_URL}"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "TPW" # Teczki Polskiego Wrestlingu. In English, Tales of Polish Wrestling

theme = "mensch"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here
new_issue_url = "https://github.com/k3rni/teczki-polskiego-wrestlingu/issues/new"

# Add an org here if it has its own subdirectory under e/
org_events_dir = {'ddw' = true, 'kpw' = true, 'ptw' = true, 'mzw' = true, 'tbw' = true}

list_pages = false
default_theme = "dark"
mensch_links = [
  { path = "@/a/contributing.md", name = "Contributing", icon="edit" },
  { url = "//github.com/k3rni/teczki-polskiego-wrestlingu", name = "GitHub", icon="github" }
]
mensch_theme = "theme-base-0e"
cloudflare = true

[extra.org_styles.ppw]
bg = '#5b007e'
fg = '#c7c7c7'
text = 'PpW'

[extra.org_styles.mzw]
bg = '#208315'

[extra.org_styles.kpw]
bg = '#133762'

[extra.org_styles.ddw]
bg = '#71171f'

[extra.org_styles.tbw]
bg = '#0400cd'
fg = '#8c8d87'